name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Simulate deploy
        run: echo "Deploy simulado com sucesso!"

