name: Enviar alerta para o Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  discord_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: " Novo push ou merge detectado no repositório!"
